# Generated by Django 3.0.8 on 2020-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0003_auto_20200714_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='item_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
